Добавляет наставника
htmlacademy-javascript/2217971-kekstagram-27 pull request #1
Opened 2022-10-21 18:25 UTC by Lokoxa

2022-10-22 09:32 UTC, nlold requested changes
Небольшая правочка нужна

2022-10-22 09:32 UTC, nlold commented on Readme.md
> +* Наставник: `Никита Любицкий`.
И еще ссылочку на профиль тут надо оставить =)

2022-10-22 11:52 UTC, Lokoxa commented on Readme.md
> +* Наставник: `Никита Любицкий`.
а где ее взять?

2022-10-23 03:31 UTC, nlold approved these changes

2022-10-23 03:31 UTC, merged